package Parchis;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

public class JPanelTableroParchis extends javax.swing.JPanel {

    //private JFrame jFramePadre;
    public JPanelTableroParchis() {
        initComponents();
        readBackgroundFile();
        this.setSize(600, 600);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    Image image;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    // private URL url = getClass().getResource("/Images/Parchis_800px.png");
    // Image image = new ImageIcon(url).getImage();
    @Override
    public void paintComponent(Graphics g) {
        //URL url = getClass().getResource("/Images/Parchis_800px.png");
        //Dimension tamanio = getSize();
        int dim = Math.min(this.getParent().getWidth(), this.getParent().getHeight());
        //image = image.getScaledInstance(this.getWidth(), this.getHeight(), java.awt.Image.SCALE_SMOOTH);
        g.drawImage(image, 0, 0, dim, dim, this);
        //System.out.println("parent: " + this.getParent().getWidth() + " , " + this.getParent().getHeight());
        //System.out.println("this: " + this.getWidth() + " , " + this.getHeight());
        //System.out.println("tamanio=" + tamanio.toString());
        this.setOpaque(false);
        super.paintComponent(g);
    }

    /*
    public JFrame getjFramePadre() {
        return jFramePadre;
    }

    public void setjFramePadre(JFrame jFramePadre) {
        this.jFramePadre = jFramePadre;
    }*/
    private void readBackgroundFile() {

        this.image = new ImageIcon(getClass().getResource("/Images/600px-Parchís.svg.png")).getImage();

    }
}
