/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parchis;

import java.util.Arrays;

/**
 *
 * @author Paco
 */
public class PlayersOptionsPanel extends javax.swing.JFrame {

    boolean[] PlayerIsHuman;

    /**
     * Creates new form PlayersOptionsPanel
     *
     * @param PlayerIsHuman
     */
    public PlayersOptionsPanel(boolean[] PlayerIsHuman) {
        initComponents();
        setLocationRelativeTo(null);
        this.PlayerIsHuman = new boolean[4];
        this.PlayerIsHuman = PlayerIsHuman;
    }

    private PlayersOptionsPanel() {
        initComponents();
        setLocationRelativeTo(null);
        this.PlayerIsHuman = new boolean[4];
        for (boolean player : this.PlayerIsHuman) {
            player = false;
        }
        //this.PlayerIsHuman={false,false,false,false};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BGYellow = new javax.swing.ButtonGroup();
        BGGreen = new javax.swing.ButtonGroup();
        BGRed = new javax.swing.ButtonGroup();
        BGBlue = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPYellow = new javax.swing.JPanel();
        RBYellowHuman = new javax.swing.JRadioButton();
        RBYellowComputer = new javax.swing.JRadioButton();
        jPGreen = new javax.swing.JPanel();
        RBGreenHuman = new javax.swing.JRadioButton();
        RBGreenComputer = new javax.swing.JRadioButton();
        jPRed = new javax.swing.JPanel();
        RBRedHuman = new javax.swing.JRadioButton();
        RBRedComputer = new javax.swing.JRadioButton();
        jPBlue = new javax.swing.JPanel();
        RBBlueHuman = new javax.swing.JRadioButton();
        RBBlueComputer = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPYellow.setBackground(new java.awt.Color(255, 255, 51));
        jPYellow.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Yellow", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPYellow.setLayout(new javax.swing.BoxLayout(jPYellow, javax.swing.BoxLayout.Y_AXIS));

        BGYellow.add(RBYellowHuman);
        RBYellowHuman.setText("Human");
        jPYellow.add(RBYellowHuman);

        BGYellow.add(RBYellowComputer);
        RBYellowComputer.setSelected(true);
        RBYellowComputer.setText("Computer");
        jPYellow.add(RBYellowComputer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPYellow, gridBagConstraints);

        jPGreen.setBackground(new java.awt.Color(0, 153, 51));
        jPGreen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Green", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPGreen.setLayout(new javax.swing.BoxLayout(jPGreen, javax.swing.BoxLayout.Y_AXIS));

        BGGreen.add(RBGreenHuman);
        RBGreenHuman.setText("Human");
        jPGreen.add(RBGreenHuman);

        BGGreen.add(RBGreenComputer);
        RBGreenComputer.setSelected(true);
        RBGreenComputer.setText("Computer");
        jPGreen.add(RBGreenComputer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPGreen, gridBagConstraints);

        jPRed.setBackground(new java.awt.Color(204, 0, 0));
        jPRed.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Red", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPRed.setForeground(new java.awt.Color(0, 0, 0));
        jPRed.setLayout(new javax.swing.BoxLayout(jPRed, javax.swing.BoxLayout.Y_AXIS));

        BGRed.add(RBRedHuman);
        RBRedHuman.setText("Human");
        jPRed.add(RBRedHuman);

        BGRed.add(RBRedComputer);
        RBRedComputer.setSelected(true);
        RBRedComputer.setText("Computer");
        jPRed.add(RBRedComputer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPRed, gridBagConstraints);

        jPBlue.setBackground(new java.awt.Color(0, 153, 204));
        jPBlue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPBlue.setLayout(new javax.swing.BoxLayout(jPBlue, javax.swing.BoxLayout.Y_AXIS));

        BGBlue.add(RBBlueHuman);
        RBBlueHuman.setText("Human");
        jPBlue.add(RBBlueHuman);

        BGBlue.add(RBBlueComputer);
        RBBlueComputer.setSelected(true);
        RBBlueComputer.setText("Computer");
        jPBlue.add(RBBlueComputer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPBlue, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.setMinimumSize(new java.awt.Dimension(78, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jButton1, gridBagConstraints);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.PlayerIsHuman[0] = RBYellowHuman.isSelected();
        this.PlayerIsHuman[1] = RBGreenHuman.isSelected();
        this.PlayerIsHuman[2] = RBRedHuman.isSelected();
        this.PlayerIsHuman[3] = RBBlueHuman.isSelected();
        System.out.println(Arrays.toString(this.PlayerIsHuman));
        Parchis myGame = new Parchis(this.PlayerIsHuman);
        this.dispose();
        myGame.play();
        //return PlayerIsHuman;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayersOptionsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayersOptionsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayersOptionsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayersOptionsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PlayersOptionsPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGBlue;
    private javax.swing.ButtonGroup BGGreen;
    private javax.swing.ButtonGroup BGRed;
    private javax.swing.ButtonGroup BGYellow;
    private javax.swing.JRadioButton RBBlueComputer;
    private javax.swing.JRadioButton RBBlueHuman;
    private javax.swing.JRadioButton RBGreenComputer;
    private javax.swing.JRadioButton RBGreenHuman;
    private javax.swing.JRadioButton RBRedComputer;
    private javax.swing.JRadioButton RBRedHuman;
    private javax.swing.JRadioButton RBYellowComputer;
    private javax.swing.JRadioButton RBYellowHuman;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPBlue;
    private javax.swing.JPanel jPGreen;
    private javax.swing.JPanel jPRed;
    private javax.swing.JPanel jPYellow;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    boolean[] getPlayerIsHuman() {
        return PlayerIsHuman;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
